services:
  go:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./backend/cmd:/app/cmd
      - ./backend/internal:/app/internal
      - ./backend/pkg:/app/pkg
      - ./backend/static:/app/static
      - ./backend/scripts:/app/scripts
      - ./backend/.air.toml:/app/.air.toml
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

      - REDIS_URL=${REDIS_URL}

      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}

      - DOMAIN=${DOMAIN}
      - GO_PORT=${GO_PORT}
    ports:
      - "80:${GO_PORT}"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13
    volumes:
      - ./postgresInit:/docker-entrypoint-initdb.d
    # issues with permissions on linux. Somehow is fine on mac
      # - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  db_data:

networks:
  default:
    driver: bridge