services:
  next:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:${NEXT_PORT}"

  go:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./backend:/app
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - REDIS_URL=${REDIS_URL}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - DOMAIN=${DOMAIN}
      - GO_PORT=${GO_PORT}
      - FRONTEND=http://${NEXT_URL}:${NEXT_PORT}
    ports:
      - "${PORT}:${GO_PORT}"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13
    volumes:
      - ./postgresInit:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  db_data:

networks:
  default:
    driver: bridge