root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/web/main.go"
  bin = "./tmp/main"
  watch_dir = ["cmd", "internal"]
  watch_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]

[log]
  level = "info"
  color = true

[settings]
  include = ["*.go"]
  exclude = ["*_test.go"]